name: Build WeMod-Patcher

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore Wemod-Patcher.sln

      - name: Build solution
        run: msbuild Wemod-Patcher.sln /p:Configuration=Release

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Wemod-Patcher
          path: |
            WeModPatcher/bin/Release/**
